### PR TITLE
UI fixes and CI/CD done

### PR DESCRIPTION
**Pull request by ameysunu**

### CODE REVIEW

**Review by nayakastha — COMMENTED** [review]
Hey! Thanks for contributing to my project. I will go through the changes soon and merge it

**Comment by ameysunu** [comment]
> Hey! Thanks for contributing to my project. I will go through the changes soon and merge it

Sure! 😊

**Comment by nayakastha** [comment]
Hey! @ameysunu  The changes are really great. The UI changes are appreciated and I am really thankful for the CI/CD setup.
You are most welcome to contribute to my other projects as well. Cheers 🍻

**Comment by ameysunu** [comment]
> Hey! @ameysunu The changes are really great. The UI changes are appreciated and I am really thankful for the CI/CD setup.
> You are most welcome to contribute to my other projects as well. Cheers 🍻

Likewise! @nayakastha. You too are most welcome to contribute to my projects as well. Kudos!

**Pull request merged**
